'use client';

import React from 'react';
import { Plate, usePlateEditor } from 'platejs/react';
import type { Value } from 'platejs';
import { BasicNodesKit } from '@/components/editor/plugins/basic-nodes-kit';

// UI Components (Generated by npx shadcn@latest add @plate/...)
import { Editor, EditorContainer } from '@/components/ui/editor';
import { FixedToolbar } from '@/components/ui/fixed-toolbar';
import { MarkToolbarButton } from '@/components/ui/mark-toolbar-button';
import { ToolbarButton } from '@/components/ui/toolbar';

interface PlateEditorProps {
    initialValue?: Value;
    onChange?: (value: Value) => void;
    readOnly?: boolean;
    placeholder?: string;
}

const defaultInitialValue: Value = [
    {
        type: 'p',
        children: [{ text: '' }]
    }
];

export function PlateEditor({
    initialValue = defaultInitialValue,
    onChange,
    readOnly = false,
    placeholder = 'Type your content here...'
}: PlateEditorProps) {
    const editor = usePlateEditor({
        plugins: [...BasicNodesKit],
        value: initialValue,
        readOnly
    });

    return (
        <Plate
            editor={editor}
            onChange={({ value }) => {
                if (onChange) {
                    onChange(value);
                }
            }}
        >
            {!readOnly && (
                <FixedToolbar className="flex justify-start gap-1 rounded-t-lg border-b bg-background p-2">
                    {/* Headings */}
                    <ToolbarButton onClick={() => editor.tf.h1.toggle()} tooltip="Heading 1">
                        H1
                    </ToolbarButton>
                    <ToolbarButton onClick={() => editor.tf.h2.toggle()} tooltip="Heading 2">
                        H2
                    </ToolbarButton>
                    <ToolbarButton onClick={() => editor.tf.h3.toggle()} tooltip="Heading 3">
                        H3
                    </ToolbarButton>

                    <div className="mx-1 w-px bg-border" />

                    {/* Block Elements */}
                    <ToolbarButton onClick={() => editor.tf.blockquote.toggle()} tooltip="Quote">
                        &quot;&quot;
                    </ToolbarButton>

                    <div className="mx-1 w-px bg-border" />

                    {/* Marks */}
                    <MarkToolbarButton nodeType="bold" tooltip="Bold (⌘+B)">
                        B
                    </MarkToolbarButton>
                    <MarkToolbarButton nodeType="italic" tooltip="Italic (⌘+I)">
                        I
                    </MarkToolbarButton>
                    <MarkToolbarButton nodeType="underline" tooltip="Underline (⌘+U)">
                        U
                    </MarkToolbarButton>
                </FixedToolbar>
            )}

            <EditorContainer>
                <Editor placeholder={placeholder} className="min-h-[300px] px-4 py-2" />
            </EditorContainer>
        </Plate>
    );
}
